// 1. Create a map object.
	var mymap = L.map('map', {
    center: [-6.89, 110.63],
    zoom: 12,
    maxZoom: 15,
    minZoom: 10,
    detectRetina: true // detect whether the sceen is high resolution or not.
});


// 2. Add a base map.
	L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png').addTo(mymap);


// 3. build up a set of colors from colorbrewer's dark2 category
	var colors = chroma.scale('Set2').mode('lch').colors(14);


// 4. dynamically append style classes to this page. This style classes will be used for colorize the markers.
	for (i = 0; i < 14; i++) {
		$('head').append($("<style> .marker-color-" + (i + 1).toString() + " { color: " + colors[i] + "; font-size: 15px; text-shadow: 0 0 3px #ffffff;} </style>"));



// 5. Add geojson data
	var cellTowers = null;

	var bts = {"type": "FeatureCollection",
		"name": "bts",
		"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
		"features": [
		{ "type": "Feature", "properties": { "Field1": 1, "No": 1, "Tower_Prov": "PT. Axis Tel. Indonesia", "Site": "Ngelo Wetan", "Alamat": "Ngelo Wetan RT 03/RW 01", "Kecamatan": "Mijen", "Long_DD": 110.72, "Lat_DD": -6.84, "Zonasi": 24, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.72, -6.84 ] } },
		{ "type": "Feature", "properties": { "Field1": 2, "No": 2, "Tower_Prov": "PT. Axis Tel. Indonesia", "Site": "Purwosari", "Alamat": "Purwosari RT 01/ RW 04", "Kecamatan": "Sayung", "Long_DD": 110.51, "Lat_DD": -6.95, "Zonasi": 1, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -6.95 ] } },
		{ "type": "Feature", "properties": { "Field1": 3, "No": 3, "Tower_Prov": "PT. Axis Tel. Indonesia", "Site": "Trengguli", "Alamat": "Trengguli RT 03/RW 02", "Kecamatan": "Wonosalam", "Long_DD": 110.69, "Lat_DD": -6.88, "Zonasi": 64, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.69, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 4, "No": 4, "Tower_Prov": "PT. Centratama", "Site": "Botorejo", "Alamat": "Dsn. Nglorok RT 02 RW 03 Kelurahan Kadilangu", "Kecamatan": "Demak", "Long_DD": 110.65, "Lat_DD": -6.9, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.65, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 5, "No": 5, "Tower_Prov": "PT. Centratama", "Site": "Karangrejo", "Alamat": "Ds. Wonosalam RT 04 RW 04", "Kecamatan": "Wonosalam", "Long_DD": 110.63, "Lat_DD": -6.93, "Zonasi": 6, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 6, "No": 6, "Tower_Prov": "PT. Centratama", "Site": "Plumutan", "Alamat": "Tangkis RT 03 RW 03", "Kecamatan": "Guntur", "Long_DD": 110.57, "Lat_DD": -6.97, "Zonasi": 48, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.97 ] } },
		{ "type": "Feature", "properties": { "Field1": 7, "No": 7, "Tower_Prov": "PT. Centratama", "Site": "Sumberejo", "Alamat": "Sumberejo RT 01 RW 04", "Kecamatan": "Mranggen", "Long_DD": 110.52, "Lat_DD": -7.06, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -7.06 ] } },
		{ "type": "Feature", "properties": { "Field1": 8, "No": 8, "Tower_Prov": "PT. Centratama", "Site": "Brumbung 2", "Alamat": "Dsn. Ngemplak RT 05 RW 01", "Kecamatan": "Mranggen", "Long_DD": 110.52, "Lat_DD": -7.01, "Zonasi": 73, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -7.01 ] } },
		{ "type": "Feature", "properties": { "Field1": 9, "No": 9, "Tower_Prov": "PT. Centratama", "Site": "rejosari", "Alamat": "Dsn. Rejosari RT 02 RW 07", "Kecamatan": "Karangtengah", "Long_DD": 110.57, "Lat_DD": -6.9, "Zonasi": 81, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 10, "No": 10, "Tower_Prov": "PT. Centratama", "Site": "Karangtengah", "Alamat": "Dsn. Kauman RT 06 RW 03_x000D_\nDs. Sukodono", "Kecamatan": "Bonang", "Long_DD": 110.59, "Lat_DD": -6.88, "Zonasi": 83, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.59, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 11, "No": 11, "Tower_Prov": "PT. Centratama", "Site": "Bangetayu kidul", "Alamat": "Jln. Jamus Krajan RT 019 RW 01 Ds. Jamus", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.0, "Zonasi": 85, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.0 ] } },
		{ "type": "Feature", "properties": { "Field1": 12, "No": 12, "Tower_Prov": "PT. Centratama", "Site": "Kebon Batur", "Alamat": "Dusun Kebon Batur RT 007 RW 05  Ds. Kebon Batur", "Kecamatan": "Mranggen", "Long_DD": 110.49, "Lat_DD": -7.05, "Zonasi": 72, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -7.05 ] } },
		{ "type": "Feature", "properties": { "Field1": 13, "No": 13, "Tower_Prov": "PT. Centratama", "Site": "Taman Sari", "Alamat": "Dusun Karangsono RT 05 RW 02_x000D_\nDs. Karangsono", "Kecamatan": "Mranggen", "Long_DD": 110.55, "Lat_DD": -7.03, "Zonasi": 102, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 14, "No": 14, "Tower_Prov": "PT. Centratama", "Site": "Kuncir", "Alamat": "Dsn. Kuncir RT 03 RW 02", "Kecamatan": "Wonosalam", "Long_DD": 110.7, "Lat_DD": -6.9, "Zonasi": 107, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 15, "No": 15, "Tower_Prov": "PT. Centratama", "Site": "Sidomulyo", "Alamat": "Dsn. Sampit RT 02 RW 01_x000D_ Ds. Sidomulyo", "Kecamatan": "Wonosalam", "Long_DD": 110.67, "Lat_DD": -6.91, "Zonasi": 89, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.67, -6.91 ] } },
		{ "type": "Feature", "properties": { "Field1": 16, "No": 16, "Tower_Prov": "PT. Centratama", "Site": "Donorejo", "Alamat": "Dsn. Baledono RT 06 RW 01_x000D_\nDs. Donorejo", "Kecamatan": "Karangtengah", "Long_DD": 110.62, "Lat_DD": -6.95, "Zonasi": 79, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.62, -6.95 ] } },
		{ "type": "Feature", "properties": { "Field1": 17, "No": 17, "Tower_Prov": "PT. Centratama", "Site": "Pedurungan", "Alamat": "Dsn. Jamus Karang Sambung _x000D_\nRT 06 RW 03, Ds. Jamus,", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.01, "Zonasi": 71, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.01 ] } },
		{ "type": "Feature", "properties": { "Field1": 18, "No": 18, "Tower_Prov": "PT. Centratama", "Site": "menur", "Alamat": "Ds. Menur RT 01 RW 02, Karangsono", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.04, "Zonasi": 106, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 19, "No": 19, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "pamongan", "Alamat": "Ds. Pamongan RT 10 / RW 02", "Kecamatan": "Guntur", "Long_DD": 110.6, "Lat_DD": -7.01, "Zonasi": 40, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.6, -7.01 ] } },
		{ "type": "Feature", "properties": { "Field1": 20, "No": 20, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Kuripan", "Alamat": "Ds. Kuripan RT 02 / RW 02", "Kecamatan": "Karangawen", "Long_DD": 110.55, "Lat_DD": -7.04, "Zonasi": 45, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 21, "No": 21, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Menur", "Alamat": "Menur RT 02/RW 04, Dsn. Semen", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -6.99, "Zonasi": 59, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -6.99 ] } },
		{ "type": "Feature", "properties": { "Field1": 22, "No": 22, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Tamansari", "Alamat": "Tamansari RT 01/RW 01", "Kecamatan": "Mranggen", "Long_DD": 110.54, "Lat_DD": -7.01, "Zonasi": 56, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -7.01 ] } },
		{ "type": "Feature", "properties": { "Field1": 23, "No": 23, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Tambakroto", "Alamat": "Tambakroto Rt 04/RW 02", "Kecamatan": "Sayung", "Long_DD": 110.55, "Lat_DD": -6.96, "Zonasi": 32, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -6.96 ] } },
		{ "type": "Feature", "properties": { "Field1": 24, "No": 24, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Sidorejo", "Alamat": "Sidorejo RT 05/RW 01", "Kecamatan": "Sayung", "Long_DD": 110.55, "Lat_DD": -6.88, "Zonasi": 30, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 25, "No": 25, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Sukodono", "Alamat": "Ngasem wetan RT 02 RW 01 _x000D_\nDs. Sukodono", "Kecamatan": "Bonang", "Long_DD": 110.59, "Lat_DD": -6.89, "Zonasi": 83, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.59, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 26, "No": 26, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Kalianyar Wonosalam", "Alamat": "Tlogodowo RT 02 RW 02", "Kecamatan": "Wonosalam", "Long_DD": 110.66, "Lat_DD": -6.95, "Zonasi": 116, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.66, -6.95 ] } },
		{ "type": "Feature", "properties": { "Field1": 27, "No": 27, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Babad Dempet", "Alamat": "Dsn. Srekan Kidul RT 08/RW 02, Ds. Megonten", "Kecamatan": "Kebonagung", "Long_DD": 110.72, "Lat_DD": -6.98, "Zonasi": 110, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.72, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 28, "No": 28, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Demak 3", "Alamat": "Jl. Kyai Turmudzi No. 10 RT 5 RW 3, Ds. Bintoro", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.9, "Zonasi": 19, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 29, "No": 29, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Kangkung Demak", "Alamat": "Perum Palmongan Indah Blok D15 No.2 RT 7 RW 1, Ds. Batursari", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.03, "Zonasi": 92, "Tinggi_m_": 38 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 30, "No": 30, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Raden Patah", "Alamat": "Sriwulan RT 07 RW 01", "Kecamatan": "Sayung", "Long_DD": 110.49, "Lat_DD": -6.95, "Zonasi": 0, "Tinggi_m_": 36 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -6.95 ] } },
		{ "type": "Feature", "properties": { "Field1": 31, "No": 31, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Kauman-Mranggen", "Alamat": "Dk. gebangsari, Ds. Batursari RT 05 RW 32", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -7.04, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 32, "No": 32, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Margohayu", "Alamat": "Dsn. Balong RT 02 RW 01, Desa Margohayu", "Kecamatan": "Karangawen", "Long_DD": 110.53, "Lat_DD": -7.07, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.53, -7.07 ] } },
		{ "type": "Feature", "properties": { "Field1": 33, "No": 33, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "Kalitengah", "Alamat": "Dsn. Senggrong RT 005 RW 003", "Kecamatan": "Mranggen", "Long_DD": 110.52, "Lat_DD": -7.05, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -7.05 ] } },
		{ "type": "Feature", "properties": { "Field1": 34, "No": 34, "Tower_Prov": "PT. Daya Mitra Telekomunikasi", "Site": "3G Buludan", "Alamat": "Sidomulyo RT 06 RW 03", "Kecamatan": "Wonosalam", "Long_DD": 110.66, "Lat_DD": -6.91, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.66, -6.91 ] } },
		{ "type": "Feature", "properties": { "Field1": 35, "No": 35, "Tower_Prov": "PT. Era Bangun Towerindo", "Site": "Pengapon", "Alamat": "Kalianyar RT 01 RW 02", "Kecamatan": "Wonosalam", "Long_DD": 110.68, "Lat_DD": -6.94, "Zonasi": 40, "Tinggi_m_": 36 }, "geometry": { "type": "Point", "coordinates": [ 110.68, -6.94 ] } },
		{ "type": "Feature", "properties": { "Field1": 36, "No": 36, "Tower_Prov": "PT. Era Bangun Towerindo", "Site": "Dempet Gajah", "Alamat": "Ds. Kuwu RT 02 RW 01", "Kecamatan": "Dempet", "Long_DD": 110.71, "Lat_DD": -6.94, "Zonasi": 60, "Tinggi_m_": 36 }, "geometry": { "type": "Point", "coordinates": [ 110.71, -6.94 ] } },
		{ "type": "Feature", "properties": { "Field1": 37, "No": 37, "Tower_Prov": "PT. Era Bangun Towerindo", "Site": "Trengguli", "Alamat": "Trengguli RT 001 / RW 001", "Kecamatan": "Wonosalam", "Long_DD": 110.69, "Lat_DD": -6.88, "Zonasi": 64, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.69, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 38, "No": 38, "Tower_Prov": "PT. Indosat", "Site": "Demak", "Alamat": "Jl. Semboja RT 07/RW 06", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.89, "Zonasi": 20, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 39, "No": 39, "Tower_Prov": "PT. Indosat", "Site": "GKJ Demak/DCS", "Alamat": "Jl. Betengan 301, Bintoro", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.89, "Zonasi": 19, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 40, "No": 40, "Tower_Prov": "PT. Indosat", "Site": "Demak timur", "Alamat": "Bolo RT 02/RW 05", "Kecamatan": "Demak", "Long_DD": 110.68, "Lat_DD": -6.88, "Zonasi": 16, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.68, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 41, "No": 41, "Tower_Prov": "PT. Indosat", "Site": "Tambirejo 14DMK", "Alamat": "Tambirejo RT 04/RW 03", "Kecamatan": "Gajah", "Long_DD": 110.76, "Lat_DD": -6.9, "Zonasi": 37, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.76, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 42, "No": 42, "Tower_Prov": "PT. Indosat", "Site": "Guntur", "Alamat": "Ds. Guntur RT 07 / RW 02", "Kecamatan": "Guntur", "Long_DD": 110.62, "Lat_DD": -6.98, "Zonasi": 41, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.62, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 43, "No": 43, "Tower_Prov": "PT. Indosat", "Site": "Ngaluran", "Alamat": "Ngaluran RT 06/RW 02", "Kecamatan": "Karanganyar", "Long_DD": 110.74, "Lat_DD": -6.87, "Zonasi": 34, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.74, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 44, "No": 44, "Tower_Prov": "PT. Indosat", "Site": "Karanganyar", "Alamat": "Babatan RT 05/RW 05", "Kecamatan": "Karanganyar", "Long_DD": 110.8, "Lat_DD": -6.85, "Zonasi": 22, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.8, -6.85 ] } },
		{ "type": "Feature", "properties": { "Field1": 45, "No": 45, "Tower_Prov": "PT. Indosat", "Site": "Tlogorejo", "Alamat": "Ds. Tlogorejo RT 04 / RW I", "Kecamatan": "Karangawen", "Long_DD": 110.56, "Lat_DD": -7.09, "Zonasi": 44, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.56, -7.09 ] } },
		{ "type": "Feature", "properties": { "Field1": 46, "No": 46, "Tower_Prov": "PT. Indosat", "Site": "Karangtengah 14D", "Alamat": "Batu Rt 07 / RW 03", "Kecamatan": "Karangtengah", "Long_DD": 110.55, "Lat_DD": -6.93, "Zonasi": 10, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 47, "No": 47, "Tower_Prov": "PT. Indosat", "Site": "Pulosari", "Alamat": "Pulosari RT 02 / RW 02", "Kecamatan": "Karangtengah", "Long_DD": 110.6, "Lat_DD": -6.92, "Zonasi": 7, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.6, -6.92 ] } },
		{ "type": "Feature", "properties": { "Field1": 48, "No": 48, "Tower_Prov": "PT. Indosat", "Site": "Ngelo Wetan", "Alamat": "Ngelo Wetan RT 03/RW 01", "Kecamatan": "Mijen", "Long_DD": 110.72, "Lat_DD": -6.84, "Zonasi": 24, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.72, -6.84 ] } },
		{ "type": "Feature", "properties": { "Field1": 49, "No": 49, "Tower_Prov": "PT. Indosat", "Site": "Mranggen 14DMK", "Alamat": "Jl. Rayung Kusuman I ,Mranggen RT 03/RW 05 blkang puskesmas", "Kecamatan": "Mranggen", "Long_DD": 110.52, "Lat_DD": -7.03, "Zonasi": 54, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 50, "No": 50, "Tower_Prov": "PT. Indosat", "Site": "Wringinjajar", "Alamat": "Wringinjajar RT 08/ RW 03", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -6.98, "Zonasi": 55, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 51, "No": 51, "Tower_Prov": "PT. Indosat", "Site": "Pucang gading14DMK", "Alamat": "Jl. Pucang anom raya I", "Kecamatan": "Mranggen", "Long_DD": 110.49, "Lat_DD": -7.04, "Zonasi": 53, "Tinggi_m_": 55 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 52, "No": 52, "Tower_Prov": "PT. Indosat", "Site": "Kebonrojo14SMG", "Alamat": "Kebonbatur RT 03/RW 03, Batursari", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -7.05, "Zonasi": 57, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -7.05 ] } },
		{ "type": "Feature", "properties": { "Field1": 53, "No": 53, "Tower_Prov": "PT. Indosat", "Site": "Bandungrejo14DN", "Alamat": "Bandungrejo RT 06/RW 02", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.02, "Zonasi": 52, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 54, "No": 54, "Tower_Prov": "PT. Indosat", "Site": "Purwosari", "Alamat": "Purwosari RT 01/RW 03", "Kecamatan": "Sayung", "Long_DD": 110.5, "Lat_DD": -6.94, "Zonasi": 1, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -6.94 ] } },
		{ "type": "Feature", "properties": { "Field1": 55, "No": 55, "Tower_Prov": "PT. Indosat", "Site": "wedung 14DMK02", "Alamat": "Ngawen RT 01/RW 01", "Kecamatan": "Wedung", "Long_DD": 110.61, "Lat_DD": -6.8, "Zonasi": 25, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.8 ] } },
		{ "type": "Feature", "properties": { "Field1": 56, "No": 56, "Tower_Prov": "PT. Indosat", "Site": "Sidomulyo 4PTIB", "Alamat": "Sidomulyo RT 02 / RW 05, Mbrangkal", "Kecamatan": "Wonosalam", "Long_DD": 110.66, "Lat_DD": -6.91, "Zonasi": 63, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.66, -6.91 ] } },
		{ "type": "Feature", "properties": { "Field1": 57, "No": 57, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Genting Demak/Sedo", "Alamat": "Genting RT 01/RW 03", "Kecamatan": "Demak", "Long_DD": 110.7, "Lat_DD": -6.87, "Zonasi": 15, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 58, "No": 58, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Mangunjiwan", "Alamat": "Mangunjuiwan RT 05/RW 03", "Kecamatan": "Demak", "Long_DD": 110.63, "Lat_DD": -6.89, "Zonasi": 20, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 59, "No": 59, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Karanganyar", "Alamat": "Dk. Babatan RT 01/RW 05", "Kecamatan": "Karanganyar", "Long_DD": 110.8, "Lat_DD": -6.85, "Zonasi": 22, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.8, -6.85 ] } },
		{ "type": "Feature", "properties": { "Field1": 60, "No": 60, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Undaan Kidul", "Alamat": "Undaan Kidul RT 12 / RW 04", "Kecamatan": "Karanganyar", "Long_DD": 110.8, "Lat_DD": -6.89, "Zonasi": 26, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.8, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 61, "No": 61, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Jragung", "Alamat": "Ds. Wonosekar RT 01 / RW I", "Kecamatan": "Karangawen", "Long_DD": 110.56, "Lat_DD": -7.09, "Zonasi": 44, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.56, -7.09 ] } },
		{ "type": "Feature", "properties": { "Field1": 62, "No": 62, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Karangtengah", "Alamat": "Batu RT 03 / RW 07", "Kecamatan": "Karangtengah", "Long_DD": 110.56, "Lat_DD": -6.93, "Zonasi": 11, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.56, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 63, "No": 63, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Mranggen", "Alamat": "Tegalrejo RT 09/RW 01", "Kecamatan": "Mranggen", "Long_DD": 110.52, "Lat_DD": -7.03, "Zonasi": 54, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 64, "No": 64, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Pucang Gading", "Alamat": "Batursari RT 01 /RW 10", "Kecamatan": "Mranggen", "Long_DD": 110.49, "Lat_DD": -7.03, "Zonasi": 69, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 65, "No": 65, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Sayung", "Alamat": "Sriwulan RT 01/RW 02", "Kecamatan": "Sayung", "Long_DD": 110.49, "Lat_DD": -6.94, "Zonasi": 4, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -6.94 ] } },
		{ "type": "Feature", "properties": { "Field1": 66, "No": 66, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Karangawen", "Alamat": "Ds. Sidorejo RT 05 / RW 04", "Kecamatan": "Karangawen", "Long_DD": 110.6, "Lat_DD": -7.05, "Zonasi": 43, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.6, -7.05 ] } },
		{ "type": "Feature", "properties": { "Field1": 67, "No": 67, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Mranggen", "Alamat": "Jl. Medan Tenggara, Mranggen RT 09/5 Rayungkusuman", "Kecamatan": "Mranggen", "Long_DD": 110.52, "Lat_DD": -7.03, "Zonasi": 54, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 68, "No": 68, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Mranggen 4", "Alamat": "Jl. Ronggos RT 08 RW 04, Ds. Kebonbatur", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.06, "Zonasi": 57, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.06 ] } },
		{ "type": "Feature", "properties": { "Field1": 69, "No": 69, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Kebonagung", "Alamat": "Dsn. Sekar Petak RT 01 RW 04, Ds. Kebonagung", "Kecamatan": "Kebonagung", "Long_DD": 110.7, "Lat_DD": -7.02, "Zonasi": 48, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 70, "No": 70, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Bintoro", "Alamat": "Branjangan RT 09 RW 09, Bintoro", "Kecamatan": "Demak", "Long_DD": 110.65, "Lat_DD": -6.89, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.65, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 71, "No": 71, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Bilo_kauman", "Alamat": "Pundenarum RT 02 RW08", "Kecamatan": "Karangawen", "Long_DD": 110.6, "Lat_DD": -7.02, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.6, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 72, "No": 72, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Jragung", "Alamat": "Dsn. Ngrajek RT 02 RW 15, Jragung", "Kecamatan": "Karangawen", "Long_DD": 110.56, "Lat_DD": -7.12, "Zonasi": 0, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.56, -7.12 ] } },
		{ "type": "Feature", "properties": { "Field1": 73, "No": 73, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Klitih", "Alamat": "Dsn. Klitih RT 08 RW 02", "Kecamatan": "Bonang", "Long_DD": 110.57, "Lat_DD": -6.87, "Zonasi": 0, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 74, "No": 74, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Teluk", "Alamat": "Teluk RT 02 RW 02", "Kecamatan": "Karangawen", "Long_DD": 110.54, "Lat_DD": -7.06, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -7.06 ] } },
		{ "type": "Feature", "properties": { "Field1": 75, "No": 75, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Tridonorejo", "Alamat": "Dk. Bener RT 04 RW 02, Ds. Tridonorejo", "Kecamatan": "Bonang", "Long_DD": 110.58, "Lat_DD": -6.85, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.58, -6.85 ] } },
		{ "type": "Feature", "properties": { "Field1": 76, "No": 76, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Candisari", "Alamat": "Candisari RT 04 RW 02", "Kecamatan": "Mranggen", "Long_DD": 110.55, "Lat_DD": -7.02, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 77, "No": 77, "Tower_Prov": "PT. Inti Bangun Sejahtera", "Site": "Jeruk gulung", "Alamat": "Jerukgulung RT 06 RW 01", "Kecamatan": "Dempet", "Long_DD": 110.72, "Lat_DD": -6.98, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.72, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 78, "No": 78, "Tower_Prov": "PT. Linggajati", "Site": "Sayung", "Alamat": "Purwosari RT 01/RW 03", "Kecamatan": "Sayung", "Long_DD": 110.51, "Lat_DD": -6.94, "Zonasi": 1, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -6.94 ] } },
		{ "type": "Feature", "properties": { "Field1": 79, "No": 79, "Tower_Prov": "PT. Naragita Dinamika Komunika", "Site": "Bumirejo", "Alamat": "Ds. Bumirejo RT 03 / RW 7", "Kecamatan": "Karangawen", "Long_DD": 110.57, "Lat_DD": -7.04, "Zonasi": 47, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 80, "No": 80, "Tower_Prov": "PT. Naragita Dinamika Komunika", "Site": "3G Perum Plamongan", "Alamat": "Desa. Batursari RT 14 RW 05", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.03, "Zonasi": 92, "Tinggi_m_": 48 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 81, "No": 81, "Tower_Prov": "PT. Persada sokka tama", "Site": "Raji", "Alamat": "Ds. Raji RT 001 RW 002", "Kecamatan": "Demak", "Long_DD": 110.68, "Lat_DD": -6.84, "Zonasi": 68, "Tinggi_m_": 71 }, "geometry": { "type": "Point", "coordinates": [ 110.68, -6.84 ] } },
		{ "type": "Feature", "properties": { "Field1": 82, "No": 82, "Tower_Prov": "PT. Protelindo", "Site": "Betokan VI", "Alamat": "Mranak RT 01 / RW 01", "Kecamatan": "Wonosalam", "Long_DD": 110.66, "Lat_DD": -6.89, "Zonasi": 17, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.66, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 83, "No": 83, "Tower_Prov": "PT. Protelindo", "Site": "Gajah II", "Alamat": "Gajah RT 02/RW 03", "Kecamatan": "Gajah", "Long_DD": 110.74, "Lat_DD": -6.87, "Zonasi": 34, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.74, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 84, "No": 84, "Tower_Prov": "PT. Protelindo", "Site": "Karangawen II/Bramba", "Alamat": "Ds. Brambang RT 05 / RW 2", "Kecamatan": "Karangawen", "Long_DD": 110.58, "Lat_DD": -7.05, "Zonasi": 42, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.58, -7.05 ] } },
		{ "type": "Feature", "properties": { "Field1": 85, "No": 85, "Tower_Prov": "PT. Protelindo", "Site": "Bakung IV", "Alamat": "Bakung RT 01 RW 01", "Kecamatan": "Mijen", "Long_DD": 110.73, "Lat_DD": -6.83, "Zonasi": 23, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.73, -6.83 ] } },
		{ "type": "Feature", "properties": { "Field1": 86, "No": 86, "Tower_Prov": "PT. Protelindo", "Site": "Mranggen II/Kembanga", "Alamat": "Kembangarum RT 08/RW 02", "Kecamatan": "Mranggen", "Long_DD": 110.53, "Lat_DD": -7.03, "Zonasi": 50, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.53, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 87, "No": 87, "Tower_Prov": "PT. Protelindo", "Site": "Mranggen/ Rayungkusu", "Alamat": "Jl. Medan Tenggara, blkg puskesmas", "Kecamatan": "Mranggen", "Long_DD": 110.52, "Lat_DD": -7.03, "Zonasi": 54, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 88, "No": 88, "Tower_Prov": "PT. Protelindo", "Site": "Bulusari", "Alamat": "Bulusari RT 02/RW 02", "Kecamatan": "Sayung", "Long_DD": 110.54, "Lat_DD": -6.97, "Zonasi": 5, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -6.97 ] } },
		{ "type": "Feature", "properties": { "Field1": 89, "No": 89, "Tower_Prov": "PT. Protelindo", "Site": "Tompe I/Karangrejo", "Alamat": "Karangrejo Rt 02 / RW 01", "Kecamatan": "Dempet", "Long_DD": 110.73, "Lat_DD": -6.99, "Zonasi": 49, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.73, -6.99 ] } },
		{ "type": "Feature", "properties": { "Field1": 90, "No": 90, "Tower_Prov": "PT. Protelindo", "Site": "Pamongan JAW.C", "Alamat": "Ds. Pamongan RT 13/RW 02", "Kecamatan": "Guntur", "Long_DD": 110.6, "Lat_DD": -7.0, "Zonasi": 40, "Tinggi_m_": 70 }, "geometry": { "type": "Point", "coordinates": [ 110.6, -7.0 ] } },
		{ "type": "Feature", "properties": { "Field1": 91, "No": 91, "Tower_Prov": "PT. Protelindo", "Site": "Undaan lor", "Alamat": "Undaan Kidul RT 03/RW 01", "Kecamatan": "Karanganyar", "Long_DD": 110.8, "Lat_DD": -6.88, "Zonasi": 31, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.8, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 92, "No": 92, "Tower_Prov": "PT. Protelindo", "Site": "Batu", "Alamat": "Batu Rt. 3 / Rw. 2 (MI)", "Kecamatan": "Karangtengah", "Long_DD": 110.55, "Lat_DD": -6.93, "Zonasi": 10, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 93, "No": 93, "Tower_Prov": "PT. Protelindo", "Site": "Kebonagung II", "Alamat": "Kebonagung RT 01/RW 04", "Kecamatan": "Kebonagung", "Long_DD": 110.7, "Lat_DD": -7.02, "Zonasi": 48, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 94, "No": 94, "Tower_Prov": "PT. Protelindo", "Site": "Bandungrejo", "Alamat": "Bandungrejo RT 03/RW 01", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -7.03, "Zonasi": 58, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 95, "No": 95, "Tower_Prov": "PT. Protelindo", "Site": "Lo Ireng I/Gemulak", "Alamat": "Gemulak Rt 01/RW 01", "Kecamatan": "Sayung", "Long_DD": 110.53, "Lat_DD": -6.93, "Zonasi": 2, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.53, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 96, "No": 96, "Tower_Prov": "PT. Protelindo", "Site": "Demak 2/Raji", "Alamat": "Ds. Raji RT 06 RW 01", "Kecamatan": "Demak", "Long_DD": 110.68, "Lat_DD": -6.85, "Zonasi": 68, "Tinggi_m_": 71 }, "geometry": { "type": "Point", "coordinates": [ 110.68, -6.85 ] } },
		{ "type": "Feature", "properties": { "Field1": 97, "No": 97, "Tower_Prov": "PT. Protelindo", "Site": "Mlatiharjo", "Alamat": "Ds. Cangkring B RT 06 RW 02", "Kecamatan": "Karanganyar", "Long_DD": 110.79, "Lat_DD": -6.87, "Zonasi": 78, "Tinggi_m_": 71 }, "geometry": { "type": "Point", "coordinates": [ 110.79, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 98, "No": 98, "Tower_Prov": "PT. Protelindo", "Site": "Sarimulyo", "Alamat": "Dk Gili Ds. Sarimulyo RT 08 RW 02", "Kecamatan": "Kebonagung", "Long_DD": 110.68, "Lat_DD": -6.99, "Zonasi": 112, "Tinggi_m_": 71 }, "geometry": { "type": "Point", "coordinates": [ 110.68, -6.99 ] } },
		{ "type": "Feature", "properties": { "Field1": 99, "No": 99, "Tower_Prov": "PT. Protelindo", "Site": "Batu", "Alamat": "Batu Rt 02 / RW 03", "Kecamatan": "Karangtengah", "Long_DD": 110.55, "Lat_DD": -6.93, "Zonasi": 10, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 100, "No": 100, "Tower_Prov": "PT. Protelindo", "Site": "Penggaron", "Alamat": "Desa Wringinjajar RT 02 RW 03", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -6.98, "Zonasi": 87, "Tinggi_m_": 32 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 101, "No": 101, "Tower_Prov": "PT. Protelindo", "Site": "Ngemplak", "Alamat": "Ngemplak RT 05 RW 01", "Kecamatan": "Mranggen", "Long_DD": 110.53, "Lat_DD": -7.01, "Zonasi": 73, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.53, -7.01 ] } },
		{ "type": "Feature", "properties": { "Field1": 102, "No": 102, "Tower_Prov": "PT. Protelindo", "Site": "Karangsono", "Alamat": "Kampung Krajan RT 02 RW 02, Ds. Karangsono", "Kecamatan": "Mranggen", "Long_DD": 110.55, "Lat_DD": -7.02, "Zonasi": 102, "Tinggi_m_": 30 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 103, "No": 103, "Tower_Prov": "PT. Protelindo", "Site": "Jamus", "Alamat": "Kp. Karang Sambung RT 10 RW 03, Ds. Jamus", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.0, "Zonasi": 71, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.0 ] } },
		{ "type": "Feature", "properties": { "Field1": 104, "No": 104, "Tower_Prov": "PT. Protelindo", "Site": "Kalisari", "Alamat": "Krajan Selatan RT 05 RW 04_x000D_\nDs. Kalisari", "Kecamatan": "Sayung", "Long_DD": 110.52, "Lat_DD": -6.97, "Zonasi": 70, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -6.97 ] } },
		{ "type": "Feature", "properties": { "Field1": 105, "No": 105, "Tower_Prov": "PT. Protelindo", "Site": "Kuncir", "Alamat": "Kuncir RT 01 RW 02", "Kecamatan": "Wonosalam", "Long_DD": 110.7, "Lat_DD": -6.9, "Zonasi": 107, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 106, "No": 106, "Tower_Prov": "PT. Protelindo", "Site": "Jogoloyo", "Alamat": "Jogoloyo RT 03 RW 04", "Kecamatan": "Wonosalam", "Long_DD": 110.63, "Lat_DD": -6.91, "Zonasi": 88, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.91 ] } },
		{ "type": "Feature", "properties": { "Field1": 107, "No": 107, "Tower_Prov": "PT. Protelindo", "Site": "Geneng", "Alamat": "Desa Geneng RT 01 RW 02", "Kecamatan": "Mijen", "Long_DD": 110.71, "Lat_DD": -6.85, "Zonasi": 98, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.71, -6.85 ] } },
		{ "type": "Feature", "properties": { "Field1": 108, "No": 108, "Tower_Prov": "PT. Protelindo", "Site": "Kebonbatur", "Alamat": "Ds. Dongko RT 05 RW 02, Ds. Kebonbatur", "Kecamatan": "Mranggen", "Long_DD": 110.49, "Lat_DD": -7.05, "Zonasi": 72, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -7.05 ] } },
		{ "type": "Feature", "properties": { "Field1": 109, "No": 109, "Tower_Prov": "PT. Protelindo", "Site": "Donorejo", "Alamat": "Dukuh Balidono RT 08 RW 01, Kel. Donorejo", "Kecamatan": "Karangtengah", "Long_DD": 110.62, "Lat_DD": -6.95, "Zonasi": 79, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.62, -6.95 ] } },
		{ "type": "Feature", "properties": { "Field1": 110, "No": 110, "Tower_Prov": "PT. Protelindo", "Site": "Kedungwaru", "Alamat": "Ds. Kedungwaru Kidul RT 03 RW 03", "Kecamatan": "Karanganyar", "Long_DD": 110.79, "Lat_DD": -6.83, "Zonasi": 90, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.79, -6.83 ] } },
		{ "type": "Feature", "properties": { "Field1": 111, "No": 111, "Tower_Prov": "PT. Protelindo", "Site": "Sidomulyo", "Alamat": "Jl. Demak Purwodadi Km 4, Ds. Sidomulyo", "Kecamatan": "Wonosalam", "Long_DD": 110.66, "Lat_DD": -6.92, "Zonasi": 61, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.66, -6.92 ] } },
		{ "type": "Feature", "properties": { "Field1": 112, "No": 112, "Tower_Prov": "PT. Protelindo", "Site": "Jamus Krajan", "Alamat": "Dsn. Krajan RT 19 RW 01, Ds. Jamus", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.0, "Zonasi": 85, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.0 ] } },
		{ "type": "Feature", "properties": { "Field1": 113, "No": 113, "Tower_Prov": "PT. Protelindo", "Site": "Batursari", "Alamat": "Jl. Kayon RT 03/02, Batursari", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -7.04, "Zonasi": 106, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 114, "No": 114, "Tower_Prov": "PT. Protelindo", "Site": "Klitih", "Alamat": "Dsn. Klitih RT 03 RW 02, Karangrejo", "Kecamatan": "Bonang", "Long_DD": 110.57, "Lat_DD": -6.87, "Zonasi": 84, "Tinggi_m_": 70 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 115, "No": 115, "Tower_Prov": "PT. Protelindo", "Site": "Sriwulan", "Alamat": "Sriwulan RT 1 RW 1", "Kecamatan": "Sayung", "Long_DD": 110.5, "Lat_DD": -6.95, "Zonasi": 0, "Tinggi_m_": 30 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -6.95 ] } },
		{ "type": "Feature", "properties": { "Field1": 116, "No": 116, "Tower_Prov": "PT. Protelindo", "Site": "Pucang gading", "Alamat": "Dsn. Telogo RT 01 RW 08, Batursari", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.05, "Zonasi": 0, "Tinggi_m_": 40 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.05 ] } },
		{ "type": "Feature", "properties": { "Field1": 117, "No": 117, "Tower_Prov": "PT. Protelindo", "Site": "Bogorame", "Alamat": "Swalayan Aneka Jaya, Jl. Sultan Fatah No.7", "Kecamatan": "Demak", "Long_DD": 110.63, "Lat_DD": -6.9, "Zonasi": 0, "Tinggi_m_": 20 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 118, "No": 118, "Tower_Prov": "PT. Protelindo", "Site": "Bintoro Demak", "Alamat": "Krapyak Barat RT 05 RW 12, kel. Bintoro", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.89, "Zonasi": 0, "Tinggi_m_": 40 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 119, "No": 119, "Tower_Prov": "PT. Protelindo", "Site": "karanganyar", "Alamat": "Cangkring RT 25/RW 05", "Kecamatan": "Karanganyar", "Long_DD": 110.79, "Lat_DD": -6.86, "Zonasi": 21, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.79, -6.86 ] } },
		{ "type": "Feature", "properties": { "Field1": 120, "No": 120, "Tower_Prov": "PT. Protelindo", "Site": "Karangsari", "Alamat": "Karangsari Rt 01 RW 04", "Kecamatan": "Karangtengah", "Long_DD": 110.6, "Lat_DD": -6.92, "Zonasi": 7, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.6, -6.92 ] } },
		{ "type": "Feature", "properties": { "Field1": 121, "No": 121, "Tower_Prov": "PT. Protelindo", "Site": "Pucang gading14DMK", "Alamat": "Jl. Pucang anom raya, Batursari RT 08 RW 26", "Kecamatan": "Mranggen", "Long_DD": 110.49, "Lat_DD": -7.04, "Zonasi": 53, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 122, "No": 122, "Tower_Prov": "PT. Protelindo", "Site": "Sidomulyo/JCDM 016 S", "Alamat": "DS. Sidomulyo RT 01 / RW 04", "Kecamatan": "Wonosalam", "Long_DD": 110.66, "Lat_DD": -6.92, "Zonasi": 61, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.66, -6.92 ] } },
		{ "type": "Feature", "properties": { "Field1": 123, "No": 123, "Tower_Prov": "PT. Protelindo", "Site": "Guntur", "Alamat": "Ds. Guntur RT 07 / RW 02", "Kecamatan": "Guntur", "Long_DD": 110.61, "Lat_DD": -6.98, "Zonasi": 41, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 124, "No": 124, "Tower_Prov": "PT. Protelindo", "Site": "Sayung", "Alamat": "Purwosari RT 01 RW 04, selatan pasar sayung", "Kecamatan": "Sayung", "Long_DD": 110.51, "Lat_DD": -6.94, "Zonasi": 1, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -6.94 ] } },
		{ "type": "Feature", "properties": { "Field1": 125, "No": 125, "Tower_Prov": "PT. Sampoerna Tel. Ind", "Site": "Botorejo", "Alamat": "Botorejo RT 01 / RW 05", "Kecamatan": "Wonosalam", "Long_DD": 110.65, "Lat_DD": -6.9, "Zonasi": 62, "Tinggi_m_": 60 }, "geometry": { "type": "Point", "coordinates": [ 110.65, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 126, "No": 126, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Katonsari", "Alamat": "Katonsari, SMK Sunan Kalijaga", "Kecamatan": "Demak", "Long_DD": 110.62, "Lat_DD": -6.91, "Zonasi": 66, "Tinggi_m_": 35 }, "geometry": { "type": "Point", "coordinates": [ 110.62, -6.91 ] } },
		{ "type": "Feature", "properties": { "Field1": 127, "No": 127, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Sayung", "Alamat": "Bulusari RT 01/RW 02", "Kecamatan": "Sayung", "Long_DD": 110.54, "Lat_DD": -6.97, "Zonasi": 5, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -6.97 ] } },
		{ "type": "Feature", "properties": { "Field1": 128, "No": 128, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Wonosalam", "Alamat": "Wonosalam RT 03/RW 04", "Kecamatan": "Wonosalam", "Long_DD": 110.63, "Lat_DD": -6.93, "Zonasi": 6, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 129, "No": 129, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Botorejo", "Alamat": "Botorejo RT 02/RW 05", "Kecamatan": "Wonosalam", "Long_DD": 110.65, "Lat_DD": -6.9, "Zonasi": 62, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.65, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 130, "No": 130, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Botosengon", "Alamat": "Botosengon RT 02 / RW 02", "Kecamatan": "Dempet", "Long_DD": 110.7, "Lat_DD": -6.96, "Zonasi": 33, "Tinggi_m_": 50 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -6.96 ] } },
		{ "type": "Feature", "properties": { "Field1": 131, "No": 131, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Brambang", "Alamat": "Ds. Brambang  RT 01 /  RW I", "Kecamatan": "Karangawen", "Long_DD": 110.58, "Lat_DD": -7.04, "Zonasi": 47, "Tinggi_m_": 70 }, "geometry": { "type": "Point", "coordinates": [ 110.58, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 132, "No": 132, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Wedung", "Alamat": "Wedung Setinggil 2", "Kecamatan": "Wedung", "Long_DD": 110.61, "Lat_DD": -6.8, "Zonasi": 25, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.8 ] } },
		{ "type": "Feature", "properties": { "Field1": 133, "No": 133, "Tower_Prov": "PT. Solusi Tunas Pratama", "Site": "Pilangrejo", "Alamat": "Pilangrejo RT 03/RW 01", "Kecamatan": "Wonosalam", "Long_DD": 110.67, "Lat_DD": -6.93, "Zonasi": 60, "Tinggi_m_": 70 }, "geometry": { "type": "Point", "coordinates": [ 110.67, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 134, "No": 134, "Tower_Prov": "PT. TBG", "Site": "Sultan Fatah Demak", "Alamat": "Kp.Bogorame RT 002 RW 001, Mangunjiwan", "Kecamatan": "Demak", "Long_DD": 110.63, "Lat_DD": -6.9, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 135, "No": 135, "Tower_Prov": "PT. TBG", "Site": "Brumbung", "Alamat": "Brumbung RT 004 RW 002,", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -7.02, "Zonasi": 0, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 136, "No": 136, "Tower_Prov": "PT. TBG", "Site": "Moro Demak", "Alamat": "Moro Demak RT 07/II", "Kecamatan": "Bonang", "Long_DD": 110.55, "Lat_DD": -6.83, "Zonasi": 82, "Tinggi_m_": 36 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -6.83 ] } },
		{ "type": "Feature", "properties": { "Field1": 137, "No": 137, "Tower_Prov": "PT. TBG", "Site": "Gajah Kudus", "Alamat": "Gajah RT 03/RW 01", "Kecamatan": "Gajah", "Long_DD": 110.73, "Lat_DD": -6.87, "Zonasi": 35, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.73, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 138, "No": 138, "Tower_Prov": "PT. TBG", "Site": "Rimbu Kidul", "Alamat": "Ds. Rejosari RT 04 / 7", "Kecamatan": "Karangawen", "Long_DD": 110.58, "Lat_DD": -7.06, "Zonasi": 46, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.58, -7.06 ] } },
		{ "type": "Feature", "properties": { "Field1": 139, "No": 139, "Tower_Prov": "PT. TBG", "Site": "Sayung Selatan", "Alamat": "Ds. Kalisari RT 02 RW", "Kecamatan": "Sayung", "Long_DD": 110.51, "Lat_DD": -6.96, "Zonasi": 75, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -6.96 ] } },
		{ "type": "Feature", "properties": { "Field1": 140, "No": 140, "Tower_Prov": "PT. TBG", "Site": "Batu", "Alamat": "Batu RT 03 / RW 02", "Kecamatan": "Karangtengah", "Long_DD": 110.55, "Lat_DD": -6.93, "Zonasi": 10, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 141, "No": 141, "Tower_Prov": "PT. TBG", "Site": "Jragung", "Alamat": "Desa Jragung Dsn. Ngrajek RT 03 RW 17", "Kecamatan": "Karangawen", "Long_DD": 110.55, "Lat_DD": -7.12, "Zonasi": 124, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.55, -7.12 ] } },
		{ "type": "Feature", "properties": { "Field1": 142, "No": 142, "Tower_Prov": "PT. TBG", "Site": "Surodadi", "Alamat": "Dukuh Doko Payung, Ds. Tugu RT 03/RW 02", "Kecamatan": "Sayung", "Long_DD": 110.53, "Lat_DD": -6.9, "Zonasi": 76, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.53, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 143, "No": 143, "Tower_Prov": "PT. TBG", "Site": "Mlaten", "Alamat": "Ds. Geneng RT 08 RW 3", "Kecamatan": "Mijen", "Long_DD": 110.71, "Lat_DD": -6.86, "Zonasi": 98, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.71, -6.86 ] } },
		{ "type": "Feature", "properties": { "Field1": 144, "No": 144, "Tower_Prov": "PT. TBG", "Site": "Polres", "Alamat": "Jogoloyo RT 03 RW 05", "Kecamatan": "Wonosalam", "Long_DD": 110.62, "Lat_DD": -6.91, "Zonasi": 66, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.62, -6.91 ] } },
		{ "type": "Feature", "properties": { "Field1": 145, "No": 145, "Tower_Prov": "PT. TBG", "Site": "jungpasir", "Alamat": "Dukuh Bajang Lor, RT 02 RW 01_x000D_\nDs. Njung Pasir", "Kecamatan": "Wedung", "Long_DD": 110.67, "Lat_DD": -6.75, "Zonasi": 27, "Tinggi_m_": 32 }, "geometry": { "type": "Point", "coordinates": [ 110.67, -6.75 ] } },
		{ "type": "Feature", "properties": { "Field1": 146, "No": 146, "Tower_Prov": "PT. TBG", "Site": "Donorejo", "Alamat": "Dukuh Balidono, RT 06 Rw 01, Desa Donorejo", "Kecamatan": "Karangtengah", "Long_DD": 110.61, "Lat_DD": -6.95, "Zonasi": 79, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.95 ] } },
		{ "type": "Feature", "properties": { "Field1": 147, "No": 147, "Tower_Prov": "PT. TBG", "Site": "Jamus", "Alamat": "Ds. Jamus RT 02 RW 02", "Kecamatan": "Mranggen", "Long_DD": 110.5, "Lat_DD": -7.0, "Zonasi": 71, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.5, -7.0 ] } },
		{ "type": "Feature", "properties": { "Field1": 148, "No": 148, "Tower_Prov": "PT. TBG", "Site": "Wonorejo", "Alamat": "Ds. Candisari RT 03 RW 05", "Kecamatan": "Mranggen", "Long_DD": 110.56, "Lat_DD": -7.01, "Zonasi": 103, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.56, -7.01 ] } },
		{ "type": "Feature", "properties": { "Field1": 149, "No": 149, "Tower_Prov": "PT. TBG", "Site": "Mranggen 3", "Alamat": "Ds. Tamansari Dsn. Jetis RT 03 RW 02", "Kecamatan": "Mranggen", "Long_DD": 110.54, "Lat_DD": -7.01, "Zonasi": 0, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -7.01 ] } },
		{ "type": "Feature", "properties": { "Field1": 150, "No": 150, "Tower_Prov": "PT. TBG", "Site": "Mranggen 4", "Alamat": "Kembangarum RT 1 RW 4", "Kecamatan": "Mranggen", "Long_DD": 110.53, "Lat_DD": -7.03, "Zonasi": 0, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.53, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 151, "No": 151, "Tower_Prov": "PT. TBG", "Site": "Kedungwaru Lor", "Alamat": "Kedungwaru Lor RT 02 RW 01", "Kecamatan": "Karanganyar", "Long_DD": 110.78, "Lat_DD": -6.81, "Zonasi": 0, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.78, -6.81 ] } },
		{ "type": "Feature", "properties": { "Field1": 152, "No": 152, "Tower_Prov": "PT. TBG", "Site": "Bonang", "Alamat": "Tridonorejo RT 01/RW 05", "Kecamatan": "Bonang", "Long_DD": 110.57, "Lat_DD": -6.84, "Zonasi": 12, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.84 ] } },
		{ "type": "Feature", "properties": { "Field1": 153, "No": 153, "Tower_Prov": "PT. TBG", "Site": "Dempet", "Alamat": "Botosengon RT 02 / RW 02", "Kecamatan": "Dempet", "Long_DD": 110.7, "Lat_DD": -6.96, "Zonasi": 33, "Tinggi_m_": 70 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -6.96 ] } },
		{ "type": "Feature", "properties": { "Field1": 154, "No": 154, "Tower_Prov": "PT. TBG", "Site": "Bulusari", "Alamat": "Ds. Gaji RT 01 / RW 02", "Kecamatan": "Guntur", "Long_DD": 110.56, "Lat_DD": -6.99, "Zonasi": 39, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.56, -6.99 ] } },
		{ "type": "Feature", "properties": { "Field1": 155, "No": 155, "Tower_Prov": "PT. TBG", "Site": "Karangawen", "Alamat": "Ds. Karangawen RT 02 / RW 8", "Kecamatan": "Karangawen", "Long_DD": 110.57, "Lat_DD": -7.04, "Zonasi": 47, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 156, "No": 156, "Tower_Prov": "PT. TBG", "Site": "Ngawen", "Alamat": "Ds. Serangan,Dk. Krajan", "Kecamatan": "Bonang", "Long_DD": 110.6, "Lat_DD": -6.83, "Zonasi": 101, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.6, -6.83 ] } },
		{ "type": "Feature", "properties": { "Field1": 157, "No": 157, "Tower_Prov": "PT. TBG", "Site": "Mutih", "Alamat": "Jl. Pemuda RT 01 RW 04, Desa Jetak", "Kecamatan": "Wedung", "Long_DD": 110.66, "Lat_DD": -6.78, "Zonasi": 95, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.66, -6.78 ] } },
		{ "type": "Feature", "properties": { "Field1": 158, "No": 158, "Tower_Prov": "PT. TBG", "Site": "Klampok", "Alamat": "Wardoyo RT 001/RW 002 Kel. Wardoyo", "Kecamatan": "Kebonagung", "Long_DD": 110.74, "Lat_DD": -7.02, "Zonasi": 113, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.74, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 159, "No": 159, "Tower_Prov": "PT. TBG", "Site": "Jali", "Alamat": "Dukuh Keradenan RT 2/RW 4", "Kecamatan": "Bonang", "Long_DD": 110.64, "Lat_DD": -6.84, "Zonasi": 29, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.84 ] } },
		{ "type": "Feature", "properties": { "Field1": 160, "No": 160, "Tower_Prov": "PT. TBG", "Site": "Demak", "Alamat": "jl. Pemuda50 belakang puskesmas", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.89, "Zonasi": 20, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 161, "No": 161, "Tower_Prov": "PT. TBG", "Site": "Wilalung", "Alamat": "Gedangalas RT 01/RW 01", "Kecamatan": "Gajah", "Long_DD": 110.72, "Lat_DD": -6.91, "Zonasi": 36, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.72, -6.91 ] } },
		{ "type": "Feature", "properties": { "Field1": 162, "No": 162, "Tower_Prov": "PT. TBG", "Site": "cangkring barat", "Alamat": "Cangkring Rembang RT 05 RW 01", "Kecamatan": "Karanganyar", "Long_DD": 110.77, "Lat_DD": -6.87, "Zonasi": 67, "Tinggi_m_": 62 }, "geometry": { "type": "Point", "coordinates": [ 110.77, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 163, "No": 163, "Tower_Prov": "PT. TBG", "Site": "Wringinjajar", "Alamat": "Wringinjajar RT 03/RW 03", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -6.98, "Zonasi": 55, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 164, "No": 164, "Tower_Prov": "PT. TBG", "Site": "Blue Kramat", "Alamat": "Dukuh Pojok RT 07 RW 01, Harjowinangun", "Kecamatan": "Dempet", "Long_DD": 110.75, "Lat_DD": -6.93, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.75, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 165, "No": 165, "Tower_Prov": "PT. TBG", "Site": "Weding", "Alamat": "Weding RT. 02 RW 08", "Kecamatan": "Bonang", "Long_DD": 110.63, "Lat_DD": -6.83, "Zonasi": 28, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.83 ] } },
		{ "type": "Feature", "properties": { "Field1": 166, "No": 166, "Tower_Prov": "PT. TBG", "Site": "Singorejo", "Alamat": "Ds. Singorejo RT 02 RW 02", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.88, "Zonasi": 65, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 167, "No": 167, "Tower_Prov": "PT. Telkomsel", "Site": "Demak", "Alamat": "Jl. Pemuda 46", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.89, "Zonasi": 20, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 168, "No": 168, "Tower_Prov": "PT. Telkomsel", "Site": "Tridonorejo", "Alamat": "Tridonorejo RT 01/RW 05", "Kecamatan": "Bonang", "Long_DD": 110.57, "Lat_DD": -6.84, "Zonasi": 12, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.84 ] } },
		{ "type": "Feature", "properties": { "Field1": 169, "No": 169, "Tower_Prov": "PT. Telkomsel", "Site": "Kr. Mlati", "Alamat": "Karangmlati Rt.5 Rw.2", "Kecamatan": "Demak", "Long_DD": 110.61, "Lat_DD": -6.98, "Zonasi": 41, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 170, "No": 170, "Tower_Prov": "PT. Telkomsel", "Site": "Bolo Demak", "Alamat": "Ds. Bolo Kp. Gesik", "Kecamatan": "Demak", "Long_DD": 110.68, "Lat_DD": -6.88, "Zonasi": 16, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.68, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 171, "No": 171, "Tower_Prov": "PT. Telkomsel", "Site": "Botosengon", "Alamat": "Ds. Botosengon Rt.  Rw.", "Kecamatan": "Dempet", "Long_DD": 110.7, "Lat_DD": -6.96, "Zonasi": 33, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.7, -6.96 ] } },
		{ "type": "Feature", "properties": { "Field1": 172, "No": 172, "Tower_Prov": "PT. Telkomsel", "Site": "Gajah", "Alamat": "Gajah RT 02/RW 03", "Kecamatan": "Gajah", "Long_DD": 110.74, "Lat_DD": -6.87, "Zonasi": 34, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.74, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 173, "No": 173, "Tower_Prov": "PT. Telkomsel", "Site": "Guntur", "Alamat": "Ds. Guntur RT 08 / RW 01", "Kecamatan": "Guntur", "Long_DD": 110.61, "Lat_DD": -6.98, "Zonasi": 41, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.98 ] } },
		{ "type": "Feature", "properties": { "Field1": 174, "No": 174, "Tower_Prov": "PT. Telkomsel", "Site": "Gaji", "Alamat": "Ds. Gaji RT 01 / RW 01", "Kecamatan": "Guntur", "Long_DD": 110.57, "Lat_DD": -6.99, "Zonasi": 39, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.99 ] } },
		{ "type": "Feature", "properties": { "Field1": 175, "No": 175, "Tower_Prov": "PT. Telkomsel", "Site": "wonorejo", "Alamat": "Wonorejo RT 02/ RW 03", "Kecamatan": "Karanganyar", "Long_DD": 110.79, "Lat_DD": -6.86, "Zonasi": 21, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.79, -6.86 ] } },
		{ "type": "Feature", "properties": { "Field1": 176, "No": 176, "Tower_Prov": "PT. Telkomsel", "Site": "Padang", "Alamat": "Ds. Tlogorejo Rt. 1 Rw.4", "Kecamatan": "Karangawen", "Long_DD": 110.56, "Lat_DD": -7.09, "Zonasi": 44, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.56, -7.09 ] } },
		{ "type": "Feature", "properties": { "Field1": 177, "No": 177, "Tower_Prov": "PT. Telkomsel", "Site": "Kuripan", "Alamat": "Ds. Kuripan RT 01 / RW 01", "Kecamatan": "Karangawen", "Long_DD": 110.54, "Lat_DD": -7.03, "Zonasi": 51, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 178, "No": 178, "Tower_Prov": "PT. Telkomsel", "Site": "Wonokerto", "Alamat": "Wonokerto karangtowo RT 01 / RW / 01", "Kecamatan": "Karangtengah", "Long_DD": 110.58, "Lat_DD": -6.92, "Zonasi": 8, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.58, -6.92 ] } },
		{ "type": "Feature", "properties": { "Field1": 179, "No": 179, "Tower_Prov": "PT. Telkomsel", "Site": "Kebonagung", "Alamat": "Pilangwetan RT 05/RW 02", "Kecamatan": "Kebonagung", "Long_DD": 110.69, "Lat_DD": -7.02, "Zonasi": 48, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.69, -7.02 ] } },
		{ "type": "Feature", "properties": { "Field1": 180, "No": 180, "Tower_Prov": "PT. Telkomsel", "Site": "Bakung", "Alamat": "Bakung RT 01/ RW 01", "Kecamatan": "Mijen", "Long_DD": 110.73, "Lat_DD": -6.83, "Zonasi": 23, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.73, -6.83 ] } },
		{ "type": "Feature", "properties": { "Field1": 181, "No": 181, "Tower_Prov": "PT. Telkomsel", "Site": "Mranggen", "Alamat": "Mranggen RT 08/RW 03", "Kecamatan": "Mranggen", "Long_DD": 110.51, "Lat_DD": -7.03, "Zonasi": 58, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.51, -7.03 ] } },
		{ "type": "Feature", "properties": { "Field1": 182, "No": 182, "Tower_Prov": "PT. Telkomsel", "Site": "Pucang Gading", "Alamat": "Pucang Gading Pucanganom Rt.8 Rw.26 , Batursari", "Kecamatan": "Mranggen", "Long_DD": 110.49, "Lat_DD": -7.04, "Zonasi": 53, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 183, "No": 183, "Tower_Prov": "PT. Telkomsel", "Site": "Bulusari", "Alamat": "Bulusari RT 02/RW 02", "Kecamatan": "Sayung", "Long_DD": 110.54, "Lat_DD": -6.97, "Zonasi": 5, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -6.97 ] } },
		{ "type": "Feature", "properties": { "Field1": 184, "No": 184, "Tower_Prov": "PT. Telkomsel", "Site": "Sidogemah", "Alamat": "Sidogemah RT 01/RW 02", "Kecamatan": "Sayung", "Long_DD": 110.52, "Lat_DD": -6.94, "Zonasi": 3, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.52, -6.94 ] } },
		{ "type": "Feature", "properties": { "Field1": 185, "No": 185, "Tower_Prov": "PT. Telkomsel", "Site": "wedung", "Alamat": "Buko  RT 1/RW1", "Kecamatan": "Wedung", "Long_DD": 110.62, "Lat_DD": -6.79, "Zonasi": 25, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.62, -6.79 ] } },
		{ "type": "Feature", "properties": { "Field1": 186, "No": 186, "Tower_Prov": "PT. Telkomsel", "Site": "Pilangsari", "Alamat": "Pilangrejo RT 06/RW 2", "Kecamatan": "Wonosalam", "Long_DD": 110.67, "Lat_DD": -6.93, "Zonasi": 60, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.67, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 187, "No": 187, "Tower_Prov": "PT. Telkomsel", "Site": "Wonosalam", "Alamat": "wonosalam RT 03 / RW 03", "Kecamatan": "Wonosalam", "Long_DD": 110.63, "Lat_DD": -6.93, "Zonasi": 6, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.63, -6.93 ] } },
		{ "type": "Feature", "properties": { "Field1": 188, "No": 188, "Tower_Prov": "PT. Telkomsel", "Site": "Ujung pandan", "Alamat": "Botorejo RT 01 / RW 05", "Kecamatan": "Wonosalam", "Long_DD": 110.65, "Lat_DD": -6.9, "Zonasi": 62, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.65, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 189, "No": 189, "Tower_Prov": "PT. Telkomsel", "Site": "Bintoro", "Alamat": "Petengan Utara No.1324 RT 07 RW 08", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.89, "Zonasi": 0, "Tinggi_m_": 6 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.89 ] } },
		{ "type": "Feature", "properties": { "Field1": 190, "No": 190, "Tower_Prov": "PT. XL Axiata", "Site": "Bonang", "Alamat": "Jatirogo RT 02 / RW 04", "Kecamatan": "Bonang", "Long_DD": 110.59, "Lat_DD": -6.85, "Zonasi": 13, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.59, -6.85 ] } },
		{ "type": "Feature", "properties": { "Field1": 191, "No": 191, "Tower_Prov": "PT. XL Axiata", "Site": "Demak", "Alamat": "Setinggil RT 06/RW 02", "Kecamatan": "Demak", "Long_DD": 110.64, "Lat_DD": -6.9, "Zonasi": 19, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.64, -6.9 ] } },
		{ "type": "Feature", "properties": { "Field1": 192, "No": 192, "Tower_Prov": "PT. XL Axiata", "Site": "Gajah", "Alamat": "Sedo RT 06/RW 01", "Kecamatan": "Demak", "Long_DD": 110.72, "Lat_DD": -6.87, "Zonasi": 38, "Tinggi_m_": 70 }, "geometry": { "type": "Point", "coordinates": [ 110.72, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 193, "No": 193, "Tower_Prov": "PT. XL Axiata", "Site": "Karanganyar", "Alamat": "Karanganyar RT 04/RW 04", "Kecamatan": "Karanganyar", "Long_DD": 110.81, "Lat_DD": -6.85, "Zonasi": 22, "Tinggi_m_": 52 }, "geometry": { "type": "Point", "coordinates": [ 110.81, -6.85 ] } },
		{ "type": "Feature", "properties": { "Field1": 194, "No": 194, "Tower_Prov": "PT. XL Axiata", "Site": "Wonokerto", "Alamat": "Wonokerto RT 02 / RW 01", "Kecamatan": "Karangtengah", "Long_DD": 110.57, "Lat_DD": -6.92, "Zonasi": 9, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -6.92 ] } },
		{ "type": "Feature", "properties": { "Field1": 195, "No": 195, "Tower_Prov": "PT. XL Axiata", "Site": "Pucang Gading", "Alamat": "Jl. Pucang Gading Raya No. 55-G RT 09/RW 012_x000D_\n,Batursari", "Kecamatan": "Mranggen", "Long_DD": 110.49, "Lat_DD": -7.04, "Zonasi": 53, "Tinggi_m_": 72 }, "geometry": { "type": "Point", "coordinates": [ 110.49, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 196, "No": 196, "Tower_Prov": "PT. Centratama", "Site": "Sidokumpul Guntur", "Alamat": "Dukuh Wuluh RT/RW 008/003 Desa Sidokumpul", "Kecamatan": "Guntur", "Long_DD": 110.57, "Lat_DD": -7.0, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.57, -7.0 ] } },
		{ "type": "Feature", "properties": { "Field1": 197, "No": 197, "Tower_Prov": "PT. Centratama", "Site": "Bogosari Demak", "Alamat": "Dukuh Bogosari Tebasan RT/RW 005/003 Desa Bogosari", "Kecamatan": "Guntur", "Long_DD": 110.61, "Lat_DD": -6.99, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.99 ] } },
		{ "type": "Feature", "properties": { "Field1": 198, "No": 198, "Tower_Prov": "PT. Centratama", "Site": "Kalianyar 2", "Alamat": "Dukuh Kalianyar RT/RW 01/06 Desa Kalianyar", "Kecamatan": "Wonosalam", "Long_DD": 110.68, "Lat_DD": -6.96, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.68, -6.96 ] } },
		{ "type": "Feature", "properties": { "Field1": 199, "No": 199, "Tower_Prov": "PT. TBG", "Site": "Mijen", "Alamat": "Sedo RT 01 RW 02 Desa Sedo", "Kecamatan": "Demak", "Long_DD": 110.71, "Lat_DD": -6.87, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.71, -6.87 ] } },
		{ "type": "Feature", "properties": { "Field1": 200, "No": 200, "Tower_Prov": "PT. TBG", "Site": "Mranggen", "Alamat": "Kalitengah RT 04 RW 04 Desa Kalitengah", "Kecamatan": "Mranggen", "Long_DD": 110.54, "Lat_DD": -7.04, "Zonasi": 0, "Tinggi_m_": 32 }, "geometry": { "type": "Point", "coordinates": [ 110.54, -7.04 ] } },
		{ "type": "Feature", "properties": { "Field1": 201, "No": 201, "Tower_Prov": "PT. TBG", "Site": "Boyolali Gajah", "Alamat": "RT 002 RW 001 Desa Boyolali", "Kecamatan": "Gajah", "Long_DD": 110.73, "Lat_DD": -6.88, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.73, -6.88 ] } },
		{ "type": "Feature", "properties": { "Field1": 202, "No": 202, "Tower_Prov": "PT. TBG", "Site": "Mlaten Mijen", "Alamat": "RT 009 RW 001 Desa Mlaten", "Kecamatan": "Mijen", "Long_DD": 110.71, "Lat_DD": -6.84, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.71, -6.84 ] } },
		{ "type": "Feature", "properties": { "Field1": 204, "No": 204, "Tower_Prov": "PT. TBG", "Site": "Grogol Karangtengah", "Alamat": "Tempel RT 005 RW 003 Desa Grogol", "Kecamatan": "Karangtengah", "Long_DD": 110.61, "Lat_DD": -6.93, "Zonasi": 0, "Tinggi_m_": 42 }, "geometry": { "type": "Point", "coordinates": [ 110.61, -6.93 ] } }
		]
		}



	cellTowers= L.geoJson(bts,{
		onEachFeature: function (feature, layer) {
			layer.bindPopup(feature.properties.Tower_Prov);},


		pointToLayer: function (feature, latlng) {
			var id = 0;
			if (feature.properties.Tower_Prov == "PT. Axis Tel. Indonesia") { id = 0; }
			else if (feature.properties.Tower_Prov == "PT. Centratama")  { id = 1; }
			else if (feature.properties.Tower_Prov == "PT. Daya Mitra Telekomunikasi")  { id = 2; }
			else if (feature.properties.Tower_Prov == "PT. Era Bangun Towerindo")  { id = 3; }
			else if (feature.properties.Tower_Prov == "PT. Indosat")  { id = 4; }
			else if (feature.properties.Tower_Prov == "PT. Inti Bangun Sejahtera")  { id = 5; }
			else if (feature.properties.Tower_Prov == "PT. Linggajati")  { id = 6; }
			else if (feature.properties.Tower_Prov == "PT. Naragita Dinamika Komunika")  { id = 7; }
			else if (feature.properties.Tower_Prov == "Persada sokka tama")  { id = 8; }
			else if (feature.properties.Tower_Prov == "PT. Protelindo")  { id = 9; }
			else if (feature.properties.Tower_Prov == "PT. Sampoerna Tel. Ind")  { id = 10; }
			else if (feature.properties.Tower_Prov == "PT. Solusi Tunas Pratama")  { id = 11; }
			else if (feature.properties.Tower_Prov == "PT. TBG")  { id = 12; }	
			else if (feature.properties.Tower_Prov == "PT. Telkomsel")  { id = 13; }
			else { id = 14;} // "PT. XL Axiata"
			return L.marker(latlng, {icon: L.divIcon({className: 'fa fa-signal marker-color-' + (id + 1).toString() })});
			},

		attribution: 'Demak Cell Tower Data | Base Map &copy; CartoDB | Made By Manessa'
	});
	
	// Add the cellTowers to the map.
	cellTowers.addTo(mymap);